version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: lemondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresRoot

  backend:
    build:
      context: ./lemonevent
      dockerfile: Dockerfile
    volumes:
      - ./lemonevent:/rails
    depends_on:
      - db
    environment:      
      DATABASE_URL: postgres://postgres:postgresRoot@db:5432/lemondb
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./lemonfront
      dockerfile: Dockerfile
    volumes:
      - ./lemonfront:/app
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=http://localhost:3000

volumes:
  pgdata:
